# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author', models.CharField(max_length=200)),
                ('copyright', models.CharField(max_length=200)),
                ('fail_count', models.IntegerField(default=0)),
                ('feed_url', models.URLField(unique=True)),
                ('explicit', models.BooleanField(default=False)),
                ('generator', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('keywords', models.TextField()),
                ('itunes_block', models.BooleanField(default=False)),
                ('language', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_email', models.CharField(max_length=200)),
                ('published', models.DateTimeField()),
                ('site_url', models.URLField()),
                ('source', models.TextField()),
                ('pubsubhubbub', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('webmaster', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(to='podcasts.Categories')),
            ],
        ),
    ]
