# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='podcast',
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcast',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='published',
            field=models.DateTimeField(db_index=True),
        ),
    ]
