# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20161024_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='enclosure_url',
            field=models.URLField(db_index=True, default=None, unique=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='guid',
            field=models.URLField(db_index=True, default=None, unique=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='published',
            field=models.DateTimeField(db_index=True, default=None),
        ),
        migrations.AddField(
            model_name='episode',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
