# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20161024_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='published',
            field=models.DateTimeField(blank=True, db_index=True),
        ),
    ]
