# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_auto_20161024_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='pubsubhubbub',
        ),
    ]
