# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_auto_20161024_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
