# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0011_remove_podcast_webmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='explicit',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='generator',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='itunes_block',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='language',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='owner_name',
        ),
    ]
