# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0012_auto_20161025_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='copyright',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='keywords',
        ),
    ]
