# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0013_auto_20161025_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
