# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0015_auto_20161025_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='source',
        ),
    ]
