# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0016_auto_20161025_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='description',
            new_name='subtitle',
        ),
    ]
