# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0018_auto_20161025_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
