# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0021_auto_20161025_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='last_episode',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
