# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0022_podcast_last_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='post_url',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.URLField(db_index=True, default=None, max_length=500, unique=True),
        ),
    ]
